---
title: "tacoma_dailyLAI_2019"
author: "Veronica Weber"
date: "11/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
```

```{r}
####### Import Tacoma Weather Data #######

# The first step in finding the daily LAI is to import the daily weather dataset from the closest weather station. We will used data from the Tacoma Narrows Airport

# import the 2019 NCDC weather dataset which contains hourly temp, precipitation, wind and weather type observations from 01/01/2019 - 12/31/2019 collected from the TACOMA NARROWS AIRPORT, WA US (GHCND:USW00094274) weather station

weather_full <- read_csv("raw_data/tacoma_weather_daily_summary.csv") %>% 
  clean_names()

# Metadata for the variables 
#WSF2 - Fastest 2-minute wind speed
#WSF5 - Fastest 5-second wind speed
#WT03 - Thunder
#PRCP - Precipitation
#WT08 - Smoke or haze
#WDF2 - Direction of fastest 2-minute wind
#AWND - Average wind speed
#WDF5 - Direction of fastest 5-second wind
#PGTM - Peak gust time
#WT01 - Fog, ice fog, or freezing fog (may include heavy fog)
#TMAX - Maximum temperature
#WT02 - Heavy fog or heaving freezing fog (not always distinguished from fog)
#TAVG - Average Temperature.
#TMIN - Minimum temperature

# rename and isolate some of the variables we will need for looking at weather later on: average wind speed, precipitation, max, min and average temp

weather_tidy <- weather_full %>% 
  select(station,
         name,
         date,
         prcp,
         awnd,
         tmin,
         tmax,
         tavg) %>% 
  rename(wind = "awnd")

```

```{r}

###### Find First and Last Frost Dates in 2019 #######

# find minimum temperature ranges to determine the first frost (fall) and last frost (spring) which will be used for the LAI analysis. Frost means temps reach 32 degrees Fahrenheit or lower 

frost_temps <- weather_tidy %>% 
  select(date, tmin, tmax) %>% 
  filter(tmin <= 32 |
         tmax <=32) 

# frost temp table shows that the last date of frost temps was on March 11, 2019, and the first frost date was on November 21, 2019

# so leaf on date begins 3/12/19 and leaf off date begins 11/21/19

# this data set is missing data from 11/5/19 and 11/8/19, I'll add in the missing rows and then add another column that lists the calendar days which will be used for the LAI leaf on/leaf off formula

weather_tidy_day <- weather_tidy %>% 
  add_row(date = c("2019-11-05", "2019-11-18")) %>% 
  arrange(date) %>% 
  mutate(day_of_year = 1:n()) 

# create a new dataframe with just date, day of the year, and minimum and maximum LAI values
daily_lai <- weather_tidy_day %>% 
  select(date, day_of_year) %>% 
  mutate(lai_max = 4.9,
         lai_min = 0)

# export this dataframe so I can apply the LAI formula more easily in excel (I'm working on trying to find easier way to do this in r...I did it, but it's a bit messy. See the code I came up with in code chunks below)
write_csv(daily_lai, path = "data_complete/daily_lai.csv")


##### Weather DATA that is not relevant to LAI which I need to move over ######
# since data does not include average, i'll just go ahead and create a new column which averages tmin and tmax by day
# tacoma_temp_day <- weather_tidy_day %>% 
#   group_by(date, tmin, tmax) %>% 
#   mutate(t_avg = mean(c(tmin, tmax))) %>% 
#   select(station,
#          name,
#          date,
#          day_of_year,
#          prcp,
#          wind,
#          tmin,
#          tmax,
#          t_avg)

```


```{r}
##### Information about the Daily LAI formula ########

# Now that we know the leaf on and leaf off dates, it's time to factor the LAI Daily amount using the following formula from the Hirabayahsi, Nowak paper: "Comprehensive National Database of Tree Effects on Air Quality and Human Health in the United States" 

# The formula is: LAI daily = (LAI max - LAI min)/ (1 + e^-0.37(day a - day b)) + LAI min

# Where LAI max is the maximum LAI value for urban trees in Tacoma (we will use the default i-Tree value which is 4.9)

# Where LAI min for deciduous trees is 0

# We will assume LAI values will remain constant for evergreen trees at 4.9 value

# To factor the daily LAI values for deciduous trees, we will assume that deciduous trees have a 4 week/28 day transition period where they lose all of their leaves during Fall, starting at the first day of frost during the Fall season (temperatures reached 32F) on 11/21/19, and a 4-week leaf-on period during the Spring where trees grow back their leaves following the last day of frost (recorded temperatures of 32F) on 3/12/19

# For Spring - day a is the day of the year and day b is the leaf-on date 
# For Fall - day a is leaf-off date and day b is the day of the year
```


```{r}
### Ignore this code chunk - will move it later #### 
# import other datasets to compare
# mcchord_afb_hourly <- read_csv("weather/tacoma_mcchord_afb_hourly.csv")
# 
# narrows_hourly <- read_csv("weather/tacoma_narrows_hourly.csv")
```

```{r}

###### Create new datasets dividing days of year into 4 periods to apply daily LAI function ########

#  I'm having a tough time being able to filter out the specific rows/observations for daily LAI (I have to apply daily LAI values to 4 periods throughout the year). Until I find a better way, I will resort to dividing each seasonal period in the year into a seperate dataframe and then will merge all 4 together.

# I will use the daily LAI formula as mentioned above for the two 4-week leaf on/leaf off periods in the year

# I have also applied the exact same formula in Excel, and this dataframe is currently saved in the data_complete folder as "daily_lai_formula.csv"

# create new dataframe with the days of the year in which LAI is at minimum value, 0. This period starts January 1 and lasts through March 11 (the final frost date, as leaf-on period begins)

no_leaves <- weather_tidy_day %>%
  select(date, day_of_year) %>%
  group_by(day_of_year) %>%
  filter(day_of_year <= 70 |
  day_of_year >= 354) %>%
  mutate(daily_lai = 0)

# create new dataframe with the 4-week Leaf-On transition period beginning on March 12, 2019 and ending April 9, 2019

spring_leafon <- weather_tidy_day %>%
select(date, day_of_year) %>%
group_by(day_of_year) %>%
filter(day_of_year >= 71,
day_of_year <= 99) %>%
mutate(lai_min = 0,
lai_max = 4.9)

# because the day of the year values are stored as integers I'll convert to numeric class so the formula can work properly (not sure of easier way to do this)

spring_numeric <- as.numeric(spring_leafon$day_of_year)

# create new dataframe with the period in which LAI is at max value: 4.9, this period starts on April 10 and lasts through November 20.

all_leaves <- weather_tidy_day %>%
  select(date, day_of_year) %>%
  group_by(day_of_year) %>%
  filter(day_of_year >= 100,
  day_of_year <= 324) %>%
  mutate(daily_lai = 4.9)

# create new dataframe with the 4-week Leaf-Off transition period beginning on November 21, 2019 and ending December 19 2019

fall_leafoff <- weather_tidy_day %>%
  select(date, day_of_year) %>%
  group_by(day_of_year) %>%
  filter(day_of_year <= 353,
  day_of_year >= 325) %>%
  mutate(lai_min = 0,
  lai_max = 4.9)

# because the day of the year values are stored as integers I'll convert to numeric class so the formula can work properly (not sure of easier way to do this)

fall_numeric <- as.numeric(fall_leafoff$day_of_year)

##### Create Functions for Daily Leaf On and Leaf Off LAI #######

# create function for daily LAI leaf-on period in Spring
leaf_on_function <- function(day_of_year){
  daily_lai <- ((4.9 - 0) / (1+exp((-0.37)*(day_of_year - 71)))) + 0
  return(daily_lai)
  }

# Create function for daily LAI leaf-off period in Fall
leaf_off_function <- function(day_of_year){
  daily_lai <- ((4.9 - 0) / (1+exp((-0.37)*(325 - day_of_year)))) + 0
  return(daily_lai)
  }

# So I got the formula to work for leaf-on/leaf-off dates (double checked this in excel, but not sure how to merge it into the Fall data frame by dates..yet )

# For now I'll just do a workaround and will manually add the dates back

leaf_on_data <- data_frame(daily_lai = leaf_on_function(spring_numeric),
  day_of_year = 71:99)

leaf_off_data <- data_frame(daily_lai = leaf_off_function(fall_numeric),
  day_of_year = 325:353)

# Combine all of these into a dataframe

total <- full_join(no_leaves, leaf_on_data) %>%
  full_join(all_leaves) %>%
  full_join(leaf_off_data) %>%
  arrange(day_of_year) %>%
  select(-date)


# add into daily lai dataframe to combine dates
daily_lai_deciduous <- daily_lai %>%
full_join(total) %>%
select(c(-lai_max, -lai_min))

# export this dataframe so I can apply the LAI formula in excel
write_csv(daily_lai_deciduous, path = "data_complete/daily_lai_deciduous.csv")


```

