---
title: "pm2.5_flux"
author: "Veronica Weber"
date: "11/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Background 

# Methods from the Hirabayashi and Nowak study: "Comprehensive national database of tree effects on air quality and human health in the United States" - 2015
# Hourly pollutant flux per unit tree cover, F (ug m^-2 h^-1) was
# estimated as a product of the dry deposition velocity, Vd (m h^-1 ),
# and the air pollutant concentration, C (mg m^-3): F = Vd*C
# Vd for PM2.5 for unit LAI was estimated based on the median of deposition velocity measurements for varied wind speeds reported in the literature. Vd was then multiplied by LAI, and F for PM2.5 was computed accounting for the resuspension of the particles from leaves to the atmosphere due to the wind and wash-off of particles from leaves to the ground by precipitation. The detailed process for PM2.5 dry depositions is given in Nowak et al. (2013).



# Methods from the study"
# Deposition velocities of PM2.5 to trees were estimated from the literature and varied with wind speed 
# (Beckett et al., 2000b; Freer-Smith et al., 2004; Pullman, 2009). These papers measured deposition     
# velocities to tree leaves from 17 tree species under wind speeds of 1, 3, 6, 8, 9 and 10 m s^-1. For  each wind speed, the median deposition velocities from the measured deposition velocities was used to
# estimate the Vd for that wind speed per unit leaf area (Table 2). 

#The standard error of the estimates among the species was used to estimate a potential range of values of deposition velocities. The 95 percent confidence interval of median deposition velocity per wind speed was used to estimate a maximum deposition for the wind speed. As 95 percent confidence interval for the lower range of deposition velocities produced negative deposition velocities, the minimum average Vd from any species was used to represent the minimum Vd for the wind speed. 

#To estimate the Vd for wind speeds between 1 and 10 m s^-1 that did not have a measured Vd, values were interpolated between the closest measured values. For wind speeds above 10 m s^-11, the Vd for 10 m s^-1 was used; for a wind speed of 0 m s^-1, the Vd was assumed to be 0ms^-1 (Table 3).

# Resuspension of PM2.5 from trees was estimated from Pullman (2009) and varied with wind speed. This paper measured percent resuspension of PM2.5 from tree leaves of three tree species under wind speeds of 6.5, 10 and 13 m s1. The average percent resuspension for the trees species and wind speed was calculated
# (Table 3). As the percent resuspension for the wind speed of 6.5 m s1 was 9.5%, a value of 9% was assumed for a wind speed of 6 m s1 and 10% for 7 m s1. The percent resuspension for a wind speed of 0 m s1 was assumed to be 0%. To estimate the percent resuspension for wind speeds between 0 and 13 m s1 that did not have measured resuspension rates, values were interpolated from the closest measured values (or assumed value at wind speed of 0 m s1). For wind speeds above 13 m s1, the percent resuspension rate for 13 m s1 was used (Table 3).

# To calculate pollution removal, local city weather data from the National Climatic Data Center were used to obtain hourly wind speed and precipitation data. Hourly flux values to trees in the city (Eq. (1); mg m2 h1) were multiplied by total leaf surface area (m2) with hourly Vd based on local wind speed (Table 3). Flux values were accumulated hourly with a percent of the total accumulated PM2.5 over the
# current and previous hours resuspended back to the atmosphere hourly based on local wind speed. PM2.5 was accumulated upon leaves and resuspended from leaves during non-precipitation periods.

# During precipitation events, the accumulated PM2.5 was assumed to be washed off to the ground surface depending upon the magnitude of the precipitation event (Pe in mm). As leaves capture about 0.2 mm of
# precipitation (Wang et al., 2008) before runoff from the leaf, the total precipitation storage capacity (Ps in mm) of the canopy was calculated as 0.2  LAI. If Pe was greater than Ps, then all particles were assumed to be removed from the leaves and resuspension dropped to zero. When the Pe was less than Ps, no particles were removed from the leaves as there was no runoff from the leaves. After the rain stopped, PM2.5 began accumulating on and resuspending from leaves again. Water on the leaves after rain events was reduced hourly based on evaporation rates calculated from meteorological conditions. The annual flux to tree leaves was estimated as the total PM2.5 washed off leaves during the year plus the amount remaining on leaves at the end of the year.

```

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(tidyr)

######  Import Data ########


# import data set - this is hourly meterological data recorded from the Tacoma Narrows airport: 
narrows <- read_csv("raw_data/tacoma_narrows_hourly.csv") %>% 
clean_names() 

# select only the weather variables that are needed 
narrows_tidy <- narrows %>% 
  select(date, hourly_dry_bulb_temperature,
         hourly_precipitation, hourly_wind_speed,
         hourly_station_pressure,
         hourly_sea_level_pressure)

# convert the date column into proper date format for r
narrows_tidier <- as.Date(narrows_tidy$date)

# use the lubridate function in order to parse out the date and time within the column
narrows_date <- narrows_tidy %>% 
  mutate(
    date_new = lubridate::ymd_hms(date)
  )

# Found a base r command to extract the date column into year-month-date and hours-minutes-seconds
narrows_date$date_ymd <- as.Date(narrows_date$date_new)
narrows_date$date_hms <- format(narrows_date$date,"%H:%M:%S")
narrows_date$date_h <- format(narrows_date$date, "%H")

# looks like in the precipitation column, some of the values are listed at "T". According to the Local Climatological Data (LCD) summaries which provide a synopsis of climatic values for a single weather station over a specific month, a "T" value indicates a "trace" amount of precipitation. I'll replace these as 0 value. 

narrows_date_tidy <- narrows_date %>% 
  mutate(hourly_precipitation = replace(hourly_precipitation, hourly_precipitation == "T", 0))

```

```{r}

###### Find the average hourly windspeed and precipitation ######

# For the flux equation, we will need to determine the average hourly windspeeds and precipitation levels for each hour out of the year

# First, I'll create a new dataframe extracting just the wind speed values:

narrows_windspeed <- narrows_date_tidy %>% 
  select(date, hourly_wind_speed, hourly_precipitation, date_ymd, date_hms, date_h) %>% 
  group_by(date_ymd, date_h) %>% 
  summarize(mean_hourly_windspeed = mean(hourly_wind_speed, na.rm = TRUE)) 

# Next, I want to find hourly precipitation averages. First I need to find the average of precipitation values when there are NA values present in some of the observations. For whatever reason, when I originally tried writing this code and left in the summarize column to find the means of hourly precipitation with na.rm = True, it returned all NA values. So I'm doing this workaround instead:

narrows_precip_na <- narrows_date_tidy %>% 
  select(date, hourly_precipitation, date_ymd, date_hms, date_h) %>% 
  group_by(date_ymd, date_h) %>% 
  mutate(precip = case_when(is.na(hourly_precipitation) ~ mean(hourly_precipitation, na.rm = TRUE),
                            TRUE ~ as.numeric(hourly_precipitation))) 

# next I'll create a dataframe that just finds the mean of each hour's precipitation observations without factoring in the NA values 

narrows_precip <- narrows_precip_na %>% 
  select(precip, date_ymd, date_h) %>% 
  group_by(date_ymd, date_h) %>% 
  summarize(precip_final = mean(precip, na.rm = TRUE))

# combine this into the dataframe with windspeed observations and tidy up the names to reflect that they are averages: 
narrows_precip_ws <- full_join(narrows_windspeed, narrows_precip, by = c("date_ymd", "date_h")) %>% 
  rename(hourly_prcp_mean = precip_final,
         hourly_ws_mean = mean_hourly_windspeed)

# because there are some missing values in the hourly precipitation, that are recorded as NaN (not a number), I'll convert these to 0 - ideally I will substitute in the closest values at some other point. 

narrows_hourly_precip_ws_avg <- narrows_precip_ws

narrows_hourly_precip_ws_avg$hourly_prcp_mean[is.nan(narrows_hourly_precip_ws_avg$hourly_prcp_mean)] <- 0

# next, we'lll want to convert windspeed to meters/sec (is originally recorded in miles per hour) and convert precipitation to mm (is currently recorded in inches)

# 1 mph = 0.44704 meters/sec
# 1 inch = 25.4 mm

narrows_hourly_avg_converted <- narrows_hourly_precip_ws_avg %>% 
  mutate(hourly_ws_mean_ms = (hourly_ws_mean*0.44704),
         hourly_prcp_mean_mm = (hourly_prcp_mean*25.4)) %>% 
  # Because the given deposition velocities per meter/sec of given windspeed is only within 1 meter increments, I'm going to round the values to closest 1 meter using round 
  mutate(rounded_ws_ms =(round(hourly_ws_mean_ms,0))) %>% 
  mutate(rounded_prcp_mm = (round(hourly_prcp_mean_mm,2)))

# just looking at daily averages
daily_prcp <- narrows_hourly_precip_ws_avg %>% 
  select(hourly_prcp_mean, date_ymd, date_h) %>% 
  group_by(date_ymd) %>% 
  summarize(daily_prcp = sum(hourly_prcp_mean))


```

```{r}
# I'd like to export this dataframe so it will be easy to work with later
write_csv(narrows_hourly_avg_converted, path = "data_complete/narrows_hourly_avg_converted.csv")
```

```{r}
# I need a clean dataframe that just lists the hours and days of 2019 to merge other variables onto later. Since the windspeed dataframe already has these values, I'll just put them in here:

# create new data frame with hours and months
annualvalues2019 <- narrows_windspeed %>% 
  select(date_ymd, date_h)

# export this dataframe so I can use it as a reference for flux values later (displays all hours and dates of 2019)
write_csv(annualvalues2019, path = "data_complete/annualvalues2019.csv")
```

```{r}
# From the study, "Modeled PM2.5 removal by trees in ten U.S. cities and associated health effects" by Nowak et al, deposition velocity of PM2.5 to trees was estimated from the literature and varied with wind speed. (Beckett et al., 2000b; Freer-Smith et al., 2004; Pullman, 2009). These papers measured deposition velocities to tree leaves from 17 tree species under wind speeds of 1, 3, 6, 8, 9 and 10 m/sec. For each wind speed, the median deposition velocities from the measured deposition velocities was used to estimate the Vd for that wind speed per unit leaf area


# Import the deposition velocity value table which combines deposition velocity measurements in the prior (Beckett et al., 2000b; Freer-Smith et al., 2004; Pullman, 2009) studies: 

ws_dep_velocity <- tibble(wind_speed = c(1,3,6,8.5, 10),
                        median_v = c(0.030,0.152, 0.197, 0.924, 2.110),
                      standard_error = c(0.012, 0.133, 0.281, 1.610, 5.257),
                      max_v = c(0.057, 0.442,0.862, 5.063, 14.542),
                      min_v = c(0.006, 0.018, 0.029, 0.082, 0.570)
                                 )

# From the Nowak study
# Deposition velocity values and percent resuspension rates that averaged deposition velocity (Vd) that were missing values were interpolated between the closest values for windspeeds ranging from 1 - 10 m/sec. For wind speeds above 10 m/sec, the Vd for 10 m/sec was used, for a wind speed of 0, Vd was assumed to be 0.

# Resuspension of PM2.5 from trees was estimated from Pullman (2009) and varied with wind speed. This paper measured percent resuspension of PM2.5 from tree leaves of three tree species under wind speeds of 6.5, 10 and 13 m/sec. The average percent resuspension for the trees species and wind speed was calculated. To estimate the percent resuspension for wind speeds between 0 and 13 m/sec that did not have measured resuspension rates, values were interpolated from the closest measured values (or assumed value at wind speed of 0 m/sec). For wind speeds above 13 m/sec, the percent resuspension rate for 13 m/sec was used

# Import the deposition velocity and resuspension rates table from the Nowak study; 

dep_velocity_percent_resuspension <- tibble(wind_speed = c(0,1,2,3,4,5,6,7,8,9,10,11,12,13),
                                            avg_vd = c(0.00, 0.03, 0.09, 0.15, 0.17, 0.19, 0.20, 0.56, 0.92, 0.92, 2.11, 2.11, 2.11, 2.11),
                                            min_vd = c(0.000, 0.006, 0.012, 0.018, 0.022, 0.025, 0.029, 0.056, 0.082, 0.082, 0.570, 0.570, 0.570, 0.570),
                                            max_vd = c(0.000, 0.042, 0.163, 0.285, 0.349, 0.414, 0.478, 1.506, 2.534, 2.534, 7.367, 7.367, 7.367, 7.367),
                                            resuspension_pct = c(0, 0.015, 0.03, 0.045, 0.06, 0.075, 0.09, 0.10, 0.11, 0.12, 0.13, 0.16, 0.20, 0.23))

dep_velocity <- read_csv("data_complete/narrows_hourly_avg_converted.csv")

write_csv(dep_velocity_percent_resuspension, path = "data_complete/dep_velocity_percent_resuspension.csv")
```


```{r}
# Hourly flux values to trees in the city (Eq. (1); mg m2 h1) were multiplied by total leaf surface area (m2) with hourly Vd based on local wind speed (Table 3). Flux values were accumulated hourly with a percent of the total accumulated PM2.5 over the current and previous hours resuspended back to the atmosphere hourly based on local wind speed.

# During precipitation events, the accumulated PM2.5 was assumed to be washed off to the ground surface depending upon the magnitude of the precipitation event (Pe in mm). As leaves capture about 0.2 mm of precipitation (Wang et al., 2008) before runoff from the leaf, the total precipitation storage capacity (Ps in mm) of the canopy was calculated as 0.2  LAI. If Pe was greater than Ps, then all particles were assumed to be removed from the leaves and resuspension dropped to zero. When the Pe was less than Ps, no particles were removed from the leaves as there was no runoff from the leaves. After the rain stopped, PM2.5 began accumulating on and resuspending from leaves again.
```


```{r}
###### Don't pay attention to this....this is leftover code from finding hourly precipitation averages#### 

##### not yet ready to delete it yet #######

# narrows_precip_na <- narrows_date_tidy %>% 
#   select(date, hourly_precipitation, date_ymd, date_hms, date_h) %>% 
#   group_by(date_ymd, date_h) %>% 
#   mutate(precip = case_when(is.na(hourly_precipitation) ~ mean(hourly_precipitation, na.rm = TRUE),
#                             TRUE ~ as.numeric(hourly_precipitation))) 
# 
# # next I'll create a dataframe that just finds the mean of each hour's precipitation observations without factoring in the NA values 
# 
# narrows_precip <- narrows_precip_na %>% 
#   select(precip, date_ymd, date_h) %>% 
#   group_by(date_ymd, date_h) %>% 
#   summarise_each(funs(mean(precip, na.rm = TRUE))) 
#       
# # substitute the NaN (not a number) with value = 0. Though this is far from a perfect solution, it's the best guess to factor in a zero for missing precipitation values
# 
# narrows_precip$precip[is.nan(narrows_precip$precip)] <- 0
# 
#                 
# 
# narrows_precip3 <- narrows_precip %>% 
#   select(precip2, date_ymd, date_h) %>% 
#   group_by(date_ymd, date_h) %>% 
#   summarise_each(funs(mean(precip2, na.rm = TRUE))) 
#       
# narrows_rain <- narrows_date_tidy %>% 
#   select(hourly_precipitation, date_ymd, date_h) %>% 
#         group_by(date_ymd, date_h) %>% 
#         mutate_at("hourly_precipitation", function(x) replace(x, is.na(x), mean(x, na.rm = TRUE)) 
#                   
# narrows_rain_summary <- narrows_rain %>% 
#   drop_na() 
# 
# narrows_rain_summary2 <- narrows_rain_summary %>% 
#   group_by(date_ymd, date_h) %>% 
#   summarize(hourly_precip = mean(hourly_precipitation))
# 
# 
# annualvalues2019_p <- full_join(narrows_precip2, annualvalues2019, by = c("date_ymd", "date_h")) %>% 
#   replace_na(list(precip_final = 0))
# 
# annualvalues2019_p2 <- full_join(narrows_precip3, annualvalues2019, by = c("date_ymd", "date_h")) 
# 
# annualvalues2019_p2$precip2[is.nan(annualvalues2019_p2$precip2)] <- 0
# 
# # library(zoo)
# # 
# # narrows_rain1 <- narrows_date_tidy %>% 
# #   select(hourly_precipitation, date_ymd, date_h) %>% 
# #   group_by(date_ymd, date_h) %>% 
# #   mutate_at("hourly_precipitation", zoo::na.aggregate)
# # 
# # narrows_rain2 <- narrows_rain1 %>% 
# #   drop_na() %>% 
# #   group_by(date_ymd, date_h) %>% 
# #   summarise(precip = mean(hourly_precipitation)
# 
# annualvalues2019_p <- full_join(narrows_precip2, annualvalues2019, by = c("date_ymd", "date_h")) %>% 
#   replace_na(list(precip_final = 0))
```


